### ISSUE TITLE
What is this plugin for?

### ISSUE THREAD

**Issue by nazar-pc** [phpfmt/phpstorm-phpfmt#1]
It seems that PhpStorm out-of-the-box supports even more, the only exception I see is "Format on save"

**Comment by Shaked** [comment]
Hey @nazar-pc can you please elaborate? This plugin is made in order to fully support phpfmt while using phpstorm. It allows adding almost all available fmt configuration and makes sure that the buffer is being updated correctly so undoing is possible after reformat occurs.

**Comment by nazar-pc** [comment]
Sorry, I was not familiar with what is phpfmt, didn't recognize this is another existing project and thought this plugin just tries to reimplement something already present in PhpStorm. I was a bit confused, thanks for clarification.
