### ISSUE TITLE
Can not save psr2 setting

### ISSUE THREAD

**Issue by lichunqiang** [phpfmt/phpstorm-phpfmt#2]
When set the configuration, `psr1` setting can be saved.

But the `psr2` can not save....

env is `win10` and used `wamp`

![image](https://cloud.githubusercontent.com/assets/2433916/12528133/8b2f3eea-c1c8-11e5-82b2-6e694a851929.png)

**Comment by lichunqiang** [comment]
I used `.phpfmt.ini` configuration file to solve this currently.

but after the format, the content was cleaned...

Cat the event log:

```
[D:\\wamp\\bin\\php\\php5.6.11\\php.exe, C:\Users\light\.WebIde100\config\plugins\fmt.phar, --config=D:\project\private\iyuban\.phpfmt.ini, --passes="ReindentSwitchBlocks","ReindentAndAlignObjOps", -v, -o=-, -]
```

This is normal?

**Comment by Shaked** [comment]
Hey @lichunqiang,I am very sorry for these bugs.

I assume that the first bug is just something I have missed in the configuration update. 

As for the second issue, AFAIU, it seems like that the `--passes` are not being passed correctly.  

I will fix it ASAP.

**Comment by lichunqiang** [comment]
@Snaked Ok, Thanks for your work

**Comment by Shaked** [comment]
@lichunqiang I have uploaded a new version (1.0.9) to fix the issues above. 

Notice that the `passes` configuration basically shouldn't contain any quotes. 

Could you check if the new version works good for you and update\close the issue if so? 

Thank you

**Comment by lichunqiang** [comment]
@Shaked It works now. 

Thank you

**Comment by Shaked** [comment]
I am glad to hear that. I hope you keep enjoying the plugin! 

- Shaked
