### ISSUE TITLE
The PhpStormFmt Cannot format except The English character ?

### ISSUE THREAD

**Issue by wulikui** [phpfmt/phpstorm-phpfmt#3]
`<?php
function foo(){
    return '中文';
}`

@Shaked 
after formated return empty.

**Comment by Shaked** [comment]
Hey @wulikui 

This is probably a bug that I introduced. I will get back to you ASAP. 

Sorry for the inconvenience.
Shaked

**Comment by Shaked** [comment]
@wulikui 

I have tested this issue on my machine and everything seems to [work fine](https://monosnap.com/file/T9jhkJpZhYmMR8NmgrWdD4WAizz6Hw). Would you mine share more details? OS version, PhpStorm version, Java version, PhpStorm-fmt version. Also, while using the plugin please go to `Settings` -> `Other Settings` -> `PhpStorm-phpfmt` and check the `debug` option. Then, restart PhpStorm and try to reformat the code you have posted above. Once done, please check the `Event Log` (as shown in the attached screenshot) and copy paste the information from there.

Thank you!
Shaked

![eventlog](https://cloud.githubusercontent.com/assets/960015/12715339/14c7a076-c8da-11e5-859a-1747df9ed4b8.png)

**Comment by wulikui** [comment]
@Shaked 
my system: windows 7 x64
phpstorm : 10.0.3
phpfmt: 1.0.9
I am attaching the snapshot below for your reference

![image](https://cloud.githubusercontent.com/assets/4831344/12718074/0a28bae0-c927-11e5-9f14-42aaa485ab69.png)

**EN Test**
![image](https://cloud.githubusercontent.com/assets/4831344/12718183/b7323e8c-c927-11e5-8501-0b8b92f31864.png)

After formated:
![image](https://cloud.githubusercontent.com/assets/4831344/12718196/d7bae550-c927-11e5-97b4-ebc012ba2785.png)
EventLog:
![image](https://cloud.githubusercontent.com/assets/4831344/12718212/f3e98db2-c927-11e5-9c13-e2aeae6efe1f.png)

**CN Test**
![image](https://cloud.githubusercontent.com/assets/4831344/12718237/22d37a84-c928-11e5-9905-7beff8311757.png)

After formated return empty:
![image](https://cloud.githubusercontent.com/assets/4831344/12718258/49933db2-c928-11e5-989d-19f4e7599f75.png)

EventLog
![image](https://cloud.githubusercontent.com/assets/4831344/12718263/572e6906-c928-11e5-9dc6-2e8f2ee96ce6.png)

Many Thanks!

**Comment by Shaked** [comment]
Hey @wulikui 

I think I have fixed this issue, could you please try using the attached .jar instead and let me know if everything works for you? 

Thank you
Shaked

[phpstorm-phpfmt-0.1.10.zip](https://github.com/phpfmt/phpstorm-phpfmt/files/119702/phpstorm-phpfmt-0.1.10.zip)

**Comment by wulikui** [comment]
works fine! thank you @Shaked

**Comment by Shaked** [comment]
@wulikui Great! I will update the plugin now. 

Thank you for your help,
Shaked
